name: Required review check
on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    name: Checking required reviews
    runs-on: ubuntu-latest

    # GitHub should provide a "pull_request_review_target", but they don't and
    # the action will fail if run on a forked PR.
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name

    steps:
      - uses: Automattic/action-required-review@v3
        with:
          token: ${{ secrets.REQUIRED_REVIEWS_TOKEN }}
          requirements: |
            - paths: unmatched
              teams:
                - "@rcotter"
---
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  - push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name ==
      github.event.pull_request.base.repo.full_name
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }}
          event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by
          GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository
          is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the
          runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}"
      - uses: Automattic/action-required-review@v3
        with:          
          token: {{ secrets.QA_TEST_TOKEN }}}
          status: Required Review
          fail: true
          request-reviews: true
          requirements-file: .github/workflows/required-review.yaml        
